spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/zhangyusheng1314/config_repo
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8001/eureka/