spring:
  application:
    name: config
  #连接git
  cloud:
    config:
      server:
        git:
          uri: https://github.com/zhangyusheng1314/conifg_repo
          username: zhangyusheng1314
          password: zhangyusheng85
          basedir: D:/ejj
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8001/eureka/
#暴露出bus-refresh接口
management:
  endpoints:
    web:
      exposure:
        include: "*"